### ISSUE TITLE
Sorted grids on same page share state

### ISSUE THREAD

**Issue by codemasterover9000** [obogo/ux-angularjs-datagrid#108]
When two grids on the same page both use the sortModel addon and the data sets happen to have fields with the same name (like 'name', or 'date') changing the sort order for such a field on one of the grids also changes the order of the similarly named column of the other grid.

The source contains an Angular service named 'sortStatesModel'. Being an Angular service implies it to be a singleton shared by all grids. IMHO each grid should have its own instance of the sort state.

**Comment by wesjones** [comment]
The reason for the shared state is so that it remains persistent through the application in browser memory. So you can return to a page and the sort would still be applied. But I do see the issue you are referring to. I'm looking into how I can keep both. I don't have the fix yet, and this may take me a little bit to get to.

**Comment by codemasterover9000** [comment]
Hi Wes, thanks for looking into this.

The persistent sort state works great when switching between our application's main screens. However, we also maintain nested route state between screens, using https://github.com/angular-ui/ui-router. This seems to conflict with the way sortStateModel stores the sorting states.

For example, we have quite a few master-detail style screens. The master panels contain a grid, and when the user clicks on an item a nested route is opened in a detail panel. The route change causes $location.path() (used by sortStatesModel) to return a nested URL, which in turn causes getSortStateOf() to return 'undefined' for grids which are still visible, making it impossible to render a correct sorting indicator on the column headers. Clicking a column header to change sorting triggers additional sort state to be saved for the new URL.

My ideal solution would be to be able to attach the sorting state to routes, and be able to prefix it with grid names to solve my original problem.

**Comment by wesjones** [comment]
So locally what I have working is that in the params for the sortModel you can specify the "$path" that it uses to look up the paths. This will allow you to put in a specific name for that grid, and two grids on the same page can have different paths that their sorts are stored under instead of sharing the same url path.

If the $path is not provided it will default to the current implementation of the url path.

So in this [example](http://obogo.github.io/ux-angularjs-datagrid/#/sortModel) here the params that are being passed is the "sorts". You would add the '$path':'gridA' to one grid, and '$path':'gridB' to the other grid in the same page.

I have not committed this yet. I'm testing as well as waiting for your feedback on if you feel like this will solve your situation.

**Comment by wesjones** [comment]
If you provide this '$path' then it would not react to the path at all. It would only use the '$path' that it is given.

**Comment by codemasterover9000** [comment]
That sounds great. I'm looking forward to remove my ugly workaround!

**Comment by wesjones** [comment]
Awesome!, I will get this release out shortly.
That is why I think it will fix your issue completely. Each of the grids defines their own name in which their sort state is stored. So there is no sharing of state once you add this property unless you gave them all the same name. 
'$path':'all' 
If you did something like that on every page, then every page would have the same sorts.

**Comment by wesjones** [comment]
Ok, the new version is up. v1.6.9
