### ISSUE TITLE
Group Sorting

### ISSUE THREAD

**Issue by lloydmi** [obogo/ux-angularjs-datagrid#66]
I'm having a few issues with the group sorting, and I've been trying to figure them out but I have been struggling to nail down a fix. 

1. angular.extend on line 564 seems to break other functionality. For example, I have a toggle method on my prototype which is used to expand/collapse a row. After performing a sort, the extension method  is creating a new object instead of my defined model so my methods are no longer there. 

2. For my "grouped" elements, I was using a getting instead of a property so line 560 was always failing when checking for the property, and by changing it to data.ary[0][data.grouped] I was able to pass the validation, but again the extension broke the object since extend doesn't copy getters/setters.

3. When I comment out the data.ary[i] = angular.extend({}, data.ary[i]), I can get the getter working plus initial sorting. However, subsequent sorts do not update the grid. 

Any thoughts on how to work around it? 

Thanks

**Comment by wesjones** [comment]
As a quick test to see if this fixes your issue. I would like you to change the "angular.extend" to exports.extend on that line.
I have another extend that I use, and if it doesn't solve it I actually have an improved version that I may need to implement in the datagrid that will.

**Comment by lloydmi** [comment]
Preliminary tests seem to indicate that it does work and resolves the issue. 

As a side question to it and this process, my objects use the Getter/Setter pattern. Specifically the 'children' looks like the below. I can definitely modify it to use a different approach, would you recommend that we don't use this pattern for objects used within the datagrid?

            'children': {
                enumerable: true,
                get: function() {
                    return this.expanded === true ? this.__children : null;
                },
                set: function(value) {
                    this.__children = value;
                }
            },

**Comment by wesjones** [comment]
Great to hear. I will make sure that is in my next fix to the datagrid.

As for using getter setters in the data. I wouldn't recommend it. The same reason why you don't do a for loop like this.

for(var i = 0; i < items.length; i += 1) {...}

Where length is a getter it actually counts the items every time. So you loop isn't just running x time, it is counting the length every time and running x times.

To optimize you run it like this.
for(var i = 0, len = items.length; i < len; i += 1) {...}

Your getters do the same thing. Angular wraps every statement in {{}} with a watch function. It then compares for a difference in value on every digest. This now makes it so that yours are running a function within a function every time. At first this doesn't sound like a big deal. However, if you have lots of them it can become enough to be noticeable. If your getter stays simple, it is not likely to cause a noticeable difference, so it may not be bad. I just wouldn't recommend it from a performance standpoint.
