### ISSUE TITLE
Horizontal grid optimization

### ISSUE THREAD

**Issue by AlexParamonov** [obogo/ux-angularjs-datagrid#70]
Hello again.

@wesjones can you please give me a hint how to disable the height calculation and update the grid when content changes (I suppose I should set the status="active" but how to do it for the entire grid?)

I have 3 use cases:

1. Data is rendered once, no height calculation or binding needed. Just render the images and unbind. Css will take care of the rest.

2. Same as 1 but entire content should be rendered when collection replaced. It changes all at once.

3. Apply a css class to one element (mark currently playing video) and remove it from previous.

Can you give me some tips how to optimize ux datagrid for it?

**Comment by wesjones** [comment]
It sounds like you are wanting to make each of the rows a different size. 

The datagrid isn't built for that, it makes them based off of templates to calculate dom that it will not even generate until it is time. So in order to make it so that each row would have a different height, you would need a different template for each one.

If you need a different height for every item, I recommend just using a regular ng-repeat, because unless you have some way of calculating how tall it will be, it will have to create all of them anyway.

Does this answer your question?

If perhaps you want to just have it empty and then populate it, then you just give it an empty array and then give it a populated one or populate the array it has reference to. It does a deep watch so you can just change the current array by adding items.

Do just change a single row, there is an example. So for example you want to show a video in that row then you swap out the row template. It destroys the row and creates a new one right in it's place. See the expandingRow addon. I don't have an example for that one yet, but it swaps out rows so you can make rows change in size? If this is the one you are looking for I'll try to finish up the example.

**Comment by AlexParamonov** [comment]
The row is only one. The size of it is fixed as well. No height calculation requied.

The ux-grid is used on the dashboard page to showcase video grids (livetv free and below)
https://malimar.tv/dashboards/Home

When using the ng-repeat it was a hell to render and took about 10 sec. With your grid it takes less than a second.

**Comment by AlexParamonov** [comment]
Maybe I am using to complex tool for a simple task, I am the backend engineer and may sometime choose the wrong front-end tool.

**Comment by wesjones** [comment]
I see. So you are wanting to just show the videos and when they click on it then it shows the expanded view like the next page shows.

That is ideal for the expandRows addon. It just replaces that item in the grid removing one template and replacing it with another for just that particular row.

You re rendering a lot of dom. The datagrid because it does it asynchronously and in chunks is what is causing it to work faster. However, it is throwing lots of warnings because it cannot calculate the height of the rows because the rows are horizontal instead of vertical.

I think this one would be best to paginate after so many shows or build a horizontal infinite scroll so that as they scroll to the right it will load the new slides in.

**Comment by AlexParamonov** [comment]
Yes, the horizontal pagination will help a lot.
But can you give me a hint? If use the ng-repeat only, is there a way to do it asynchronously as in your grid?

It would be great to have a part of ux-datagrid extracted to the core, independent of horizontal/vertical stuff. And it will do the async rendering only.

**Comment by wesjones** [comment]
Yeah, that is actually what the core is about is chunking, viewable area analysis, and rendering.
Chunking provides the scrolling speed.
The area analysis, and rendering allow it to render as soon as possible and then run async in the background.

You wouldn't need so much, but you need to know your scrollable area and then add rows whenever you scroll to the bottom.

**Comment by AlexParamonov** [comment]
Would appreciate any help on this SO question: http://stackoverflow.com/questions/30986544/angular-ng-repeat-cache-avoid-re-rendering-on-state-change @wesjones

**Comment by wesjones** [comment]
I added a comment yesterday. Hopefully it helps.
