### ISSUE TITLE
Template height change from X to X. This can cause gaps in the datagrid.

### ISSUE THREAD

**Issue by kevin212** [obogo/ux-angularjs-datagrid#74]
Hi,

This component is fantastic. Really well done.

Unfortunately, I'm having one problem which is proving very tricky to troubleshoot.

The POCs I did using this component worked flawlessly, but now that I've implemented it in some production code, I keep getting this error for any instance of ux-datagrid, the first time that the ON_SROLL_TO_BOTTOM event fires:

"Template height change from 8 to 54. This can cause gaps in the datagrid."

I have the height of the template items hard coded in CSS to 46px, and there is a total of 8px padding. 

I'm really pulling my hair out here, trying to figure out why the first row reports a height of 8px. I see that this happens in the function: "afterRenderAfterDataChange", but cannot figure out why "oldHeight" keeps reporting as 8px first.

Any corner cases you have experienced in the past that cause this error?

(I'm using ux-angularjs-datagrid v.1.2.7.)

Many Thanks,

Kevin

**Comment by kevin212** [comment]
Follow-up:

I think the problem is the fact that in my implementation, each instance is in a container that by default is collapsed. The user can expand each container. I noticed that the "onStartupComplete" event does not fire unless the container has height (otherwise the rows do not show). 

It's still a problem and a tricky one to figure out. If you have any suggestions please let me know.

Many Thanks,

Kevin

**Comment by wesjones** [comment]
Thank you for your complements.

As for your problem, I think I know exactly what the problem is. The reason that this error is in there is because I got the same issue and needed to be notified when it happened.

With your rows if you use display: table, table-row, or table-cell then your explicit heights basically don't mean anything anymore. Tables will automatically resize to their content in the datagrid because a table row is not directly contained inside of a table tag. This is due to how the datagrid generates the dom in chunking divs to optimize it's render.

So in order to make your rows obey the explicit height instead of obeying the content internal to the table-cell's height you need to place a div inside of each table-cell field with a div that has an explicit height. 

In the example below you will notice the "YOUR CONTENT HERE" and how it is surrounded with a div that has an explicit height. This forces the table cell above it to have a content that is the height you want. Since display:table-cell only resizes to the content and not the height when the table is not structured as expected because of the datagrid chunking.

```
<div ng-controller="ctrl">
    <div class="columns-row columns-header">
        <div class="col col1">ID</div>
        <div class="col col2">First Name</div>
        <div class="col col3">Last Name</div>
        <div class="col col4">Age</div>
        <div class="col col5">Kids</div>
    </div>
    <div ux-datagrid="items">
        <script type="template/html" template-item="item">
            <div class="columns-row">
                <div class="col col1">
                    <div style="height:20px">YOUR CONTENT HERE</div>
                </div>
                <div class="col col2">
                    <div style="height:20px">YOUR CONTENT HERE</div>
                </div>
                <div class="col col3">
                    <div style="height:20px">YOUR CONTENT HERE</div>
                </div>
                <div class="col col4">
                    <div style="height:20px">YOUR CONTENT HERE</div>
                </div>
                <div class="col col5">
                    <div style="height:20px">YOUR CONTENT HERE</div>
                </div>
            </div>
        </script>
    </div>
</div>
```

**Comment by kevin212** [comment]
Thanks so much for your follow-up Wes, I really appreciate it.

My rows do not have display: table, table-row, or table-cell set at all. They are all DIVs with no specific display value set.

The more I keep going around in circles on this, the more I noticed that the "gap" was exactly the size of the viewable area. I changed ux.datagrid.options.chunks.size from 50 to 10, and now the gap is just about the size of one row. Really odd.

No matter what I do, I get that warning, and even though I have reduced the size of the gap, I cannot get rid of it. If you have any other thoughts, please do let me know.

BTW: I noticed that this component creates a "ux" global. Is that behavior intentional?

Thanks again Wes,

Kevin

**Comment by wesjones** [comment]
yes, the global ux namespace is intentional. So events can be referenced easily.

I wonder if your divs are dynamically assigning values to their heights. The datagrid calculates heights before it renders the rows. So it would check the height of an uncompiled row. This means if you are using an ng-class or some other dynamic means to add a class to a row for height it will be too late and the datagrid has already calculated the height.

If this doesn't fix it for you then lets see if we can setup a screen share next week. I am under a deadline for the rest of this week and won't have time to look at it till Monday or after.

**Comment by kevin212** [comment]
Thanks again Wes, I really appreciate you taking the time to follow-up.

I believe I might be onto the problem: top and bottom margins are being applied, which I now realize throws off the math. When I make the margin 0, it fixes the problem. The problem I still have is that if I do that in the CSS I get the console error about there being at least one row on page load, and the template does not render. If I do it manually (make margin = 0), it works, but at the moment, I cannot figure out when to apply that programatically.

I'll keep at it. I believe I am close. Will let you know if I have any specific questions.

Again, my sincere thanks Wes,

Kevin

**Comment by kevin212** [comment]
Wes,

I've got my problem figured out. It was the margins that were being added. You can resolve this issue.

Thanks again for getting back to me so quickly, I really appreciate your help.

Best Wishes,

Kevin

**Comment by wesjones** [comment]
Awesome, glad you figured it out!
