### ISSUE TITLE
Scroll bar does not indicate the total (ACTUAL) number of rows

### ISSUE THREAD

**Issue by kevin212** [obogo/ux-angularjs-datagrid#75]
Hi Wes,

Is there any way to make the scroll bar reflect the TOTAL number of elements in the actual data?

The scroll bar changes as the user scrolls down and new items are dynamically added/removed. But it does not give the user a sense of how many more elements COULD be available if they scrolled down more.

For Example:

* My data list has a total of 200 elements
* I configure the ux-datagrid component to show 10 at a time
* The scroll bar in the UI reflects that there are 10 elements after page load
* As I scroll down, the scroll bar changes to reflect that there are now 20, 30, 40 elements, etc...

Is it possible that although there are only 10 elements to start (and more are added with each scroll to bottom), the scroll bar "appears" to indicate that there are 200, so the user understands that there is MUCH more to show than just 10 elements?

Many Thanks,

Kevin

**Comment by wesjones** [comment]
It sounds like you are using the infinite scroll addon. So you are adding data as it scrolls down.
I suggest that you just load it with all 2000 and as you scroll down it will put them in. That is how it is designed to work.

What you could do is populate an array with how many elements you know there are going to be, then as the data becomes available, you extend onto that item the properties that are now keeping the instance that was already in the array. That way it would show how many there are, and as more data comes in, it just populates.

**Comment by kevin212** [comment]
Thanks a lot Wes. I have not included the  infinite scroll addon. The ux-datagrid module seems to provide infinite scrolling just fine without it. Can you please specify what functionality the infinite scroll addon provides? (I added it at first, but could not see what added functionality was there)

The approach you suggest is pretty much what I am doing. I fetch all the data in one shot (array "A"), and the template is tracking a separate array (array "B"). I populate array "B" with 20 more items from array "A" each time the user scrolls down. 

I'm trying to make the scroll bar indicate the value of array "A". (i.e. show the user that there is much more data to scroll down to than the 20, 40 or 60 they see after scrolling. ). I want the scroll bar to appear that there is 200 items in the list at all times, even when there is only 20, 40 or 60, etc...

Is this possible somehow?

Kevin

**Comment by wesjones** [comment]
Array B needs to be the length of 200, so it can show 200. Make 200 items in Array B and have them empty if you don't have the data, then add the items as you get them.

You can see infinite scroll examples here. [Infinite Scroll](http://obogo.github.io/ux-angularjs-datagrid/#/infiniteScroll)

**Comment by kevin212** [comment]
Tanks Wes,

I'm not too sure I follow you on Array B having a length of 200.

If I make Array B equal to Array A, then all 200 elements show up in the DOM, which is the opposite of what I want (I'm using this component because it ver nicely keeps only a limited number of rows in the DOM at any given time). 

If I make Array B an array with a length of 200, but no elements added yet, I get the error:

TypeError: item is undefined
childAry.max = item.max || i;

(i.e. the length is 200, but those elements are undefined).

When my async data call succeeds, create Array B and add one element to it: The FIRST element in Array A. This forces the ux-datagrid component to initialize. Then I add 20 more so that the list exceeds the height of the container (i.e. force the scroll bar). Then on each user scroll, I add 20 more.

Let me know if I am missing anything.

Thanks for the links to the infinite scroll examples. I've definitely seen them.

What I was saying is: I do not include the infinite-scroll add-on, and the ux-datagrid module provides infinite scroll just fine (i.e. this component provides the infinite scroll behaviour I needed, and I only included the file: "angular-ux-datagrid.js".) What I was asking is: What functionality does adding "ux-datagrid-infiniteScroll.js" provide? I have added that and do not see what additional functionality is provided.

Many Thanks,

Kevin

**Comment by wesjones** [comment]
The 200 elements should be empty objects "{}". Then they will not cause errors, then populate them as needed.

This whole concept seems odd for the datagrid. It's purpose it to just provide all of the data and it will render it all in dom and allow it to scroll quickly. It optimizes so that it will render what is in view and a little in both directions so that when you scroll it is already there. So it will act as if you could just render the list instantly, which with only 200 items you likely could.

So my recommendation would be to give the datagrid Array "A" so it just has all of the data, then all items will show. If you are not wanting them to render because perhaps they load images and you only want those to load when they are in view then you can change the datagrid settings to tell it how far to render in each direction. In the datagrid there are options that you can change. These options start in angular-ux-datagrid.js around line 165 - 243. They give options you can change, with comments as to what each one does. You can change the ux.datagrid.options.creepLimit=10. That means that it will only render 10 in each direction from the viewable area. Currently it is defaulted to 500. So it is rendering your whole list as quickly as it can.

You only use the infinite scroll addon if you want it to load more items when you scroll to the bottom, so it shows a spinner while you load more items and then updates with those items.

**Comment by kevin212** [comment]
Thanks very much Wes. I do understand what you are saying.

One problem I am wresting with when using your suggested approach is: My rows have a data-ng-click event attribute. That click updates a $scope property, and the UI changes based on its value (it's just a checkmark that changes to a "+", and vice verse). 

For some reason, the first 2 or 3 rows in the list work fine, but for each instance of the scroller, rows starting at about 3 or 4 don't work. It's as if the $scope property that is being toggled does not update (but it definitely does because that change triggers other behaviour, which works fine)

This is all part of a $digest cycle, so using $scope.$apply would be redundant.

If you have any thoughts, please let me know. This one is proving quite tricky to resolve.

Many Thanks,

Kevin

**Comment by wesjones** [comment]
Your welcome.

I'm not sure if I got it right. This is my best guess at the direction you are going without looking at your code.

The datagrid like ng-repeat creates a child scope for each row. So if you are wanting to update a property on the parent scope (the one the grid is on) you could only do it through $scope.$parent because the inherited value is overridden on each row's scope. 

I recommend making sure that you use objects for values on your scope if you need to manipulate properties on the parent, so they share the instance. (parent scope would have options.something).

Child scope then would change (options.something="something else") and the parent then gets it because inheritance make the options there and the options becomes a shared instance between the two. Where if you just set a primitive type on the scope, it overrides that value that it inherited from the parent.

If this doesn't help solve it. Please include the html of your template and then we will see if that can shed more light.

**Comment by kevin212** [comment]
Sorry for the slow reply on this Wes. Your answer was very helpful. Please consider this defect resolved.

Kevin
