### ISSUE TITLE
Extra element added to grid

### ISSUE THREAD

**Issue by robhicks** [obogo/ux-angularjs-datagrid#76]
I've noticed an extra data element seems to get added to the grid. 
See this [plunker](http://plnkr.co/edit/qODetwJG0YY4GcfLSUfz?p=preview). At the end of scroll region, a blank line exists. The same thing happens in the app I'm hoping to use the datagrid.
Am I doing something wrong? 
I simply was trying to recreate your infiniteScroll example because in my app, I can't get infiniteScroll to work. I receive the ux.datagrid.events.ON_STARTUP_COMPLETE but never see the ux.datagrid.events.ON_SCROLL_TO_BOTTOM event.  Any suggestions you might have for debugging the problem are welcome.

**Comment by wesjones** [comment]
The infiniteScroll addon adds that extra row to show the spinner on as long as you have not reached the limit. So as soon as you see the spinner it calls to load more data. So you can make an async call and when it loads it then populates the data down and the spinner is at the bottom again.

However, in your plunker example you have the limit too high. If you change the limit to 50, then it will not show the row at the bottom, because it is not waiting for more data.

I am also not seeing the spinner animation in your example as well. You may want to style that div yourself.

In the example [here](http://obogo.github.io/ux-angularjs-datagrid/#/infiniteScroll) you will notice that it styles the loading row.

```
.infiniteScrollEx-row {
    background-color:#efefef;
    height: 20px;
    line-height: 20px;
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
}
.infiniteScrollEx-row:nth-child(odd) {
    background-color:#dfdfdf;
}
.infiniteScrollEx-row.loading-row {
    height: 20px;
    background-color: #999;
    color: #FFF;
    text-align: center;
    vertical-align: middle;
    line-height: 20px;
}
```

**Comment by robhicks** [comment]
@wesjones Thanks for the info!

**Comment by wesjones** [comment]
You welcome :)
