### ISSUE TITLE
UX-data grid sorting in not working after one way data binding

### ISSUE THREAD

**Issue by ashpareek** [obogo/ux-angularjs-datagrid#81]
IN our grid we don't needed two way data binding as that grid is use to show data only. so we switch to one way data binding instead of two way data binding but after it we are not able to sort our grid .
we have used sortmodel addon for sorting.
Could you please help us on this?

**Comment by wesjones** [comment]
The datagrid in order to optimize the rendering after sorting is recycling the dom elements. It is changing up the scope properties on the sort since it knows it has just as many rows as it did before, so it doesn't have to rebuild them. This allows it to render faster.

With that being done, unless you have 2-way data binding it will not render the changes on the scope because the watchers are removed on a one way bind.

You may try doing an update() on the datagrid after the sort.
ux.datagrid.getGrid($scope).update();
Not really sure if that will work. Let me know. We may need to setup a jsfiddle to debug it.
