### ISSUE TITLE
chunk height much larger than its content

### ISSUE THREAD

**Issue by ittayd** [obogo/ux-angularjs-datagrid#82]
check out https://script.google.com/a/macros/drors.net/s/AKfycby32Z9cWc1xsx3u0Buu4YvvLjD84WeFTkvTZxggkq0S/dev?mode=datagrid. The first chunk is of size 1960, where is should be more like 1200. I can set a fixed height for rows, but then if some cells have long content that is wrapped in the cell (heigher height), it messes with the rest of the items

**Comment by ittayd** [comment]
I noticed this: "Template height change from 40 to 24. This can cause gaps in the datagrid.". But, I don't dynamically change the height of the template.

**Comment by wesjones** [comment]
The way to handle this is to wrap the content inside of each cell with a div and set it to overlay hidden. Table cells are disobedient to style heights, instead they size to their content.
The datagrid only makes one attempt to calculate heights since they are expensive to do, so it creates a dummy at the start of the datagrid's template creation and uses that height value to calculate. If you have content that wraps, it increases the height and gives you a false value. Here is how it should be done below to avoid it from wrapping content and throwing off the height.

Your styles may then after a row has been digested be smaller, but if predigested are taller you get this error if you haven't nested the divs correctly so they can handle overflowing.

```
<div style="display:table-cell">
   <div style="display:block;overflow:hidden;width:100px;height:20px;">
      ... now all of your content that may wrap here. It is safely contained inside of a div that will hide it if it wraps too high. 
   </div>
</div>
```
