### ISSUE TITLE
Ideas to implement variable row height

### ISSUE THREAD

**Issue by bronzovik** [obogo/ux-angularjs-datagrid#85]
I'm trying to implement variable row height support (we need ALL rows to expand upon event). The idea is to create one template per row of data by inheriting from the base template and overriding height property. Upon all rows expansion the new dataset is created with a unique template per row and is supplied to the grid.

This works pretty well up to a certain point. Several problems here:
1) ```afterRenderAfterDataChange()``` only triggers ```inst.templateModel.updateTemplateHeights()``` if the first template height is different, which is not always the case. This is easy to circumvent by forcing update.
2) ```inst.templateModel.updateTemplateHeights``` only recalculates for an active range. No other calculation is done when rows are scrolled into viewport => :boom:

Any suggestions on how to implement that gracefully would be really helpful.

**Comment by wesjones** [comment]
I actually use this a lot in the project I originally built the datagrid for. How I prefer to handle this is with the expandRows addon.

You can see an example [here](http://obogo.github.io/ux-angularjs-datagrid/#/expandableRow) that just makes that row taller. Or you can also switch it with a totally different template, which is what I am doing in another project because when it expands it has so much more dom. So I keep the rows lighter weight until they are expanded.

To do the swap of the template you can use something like this in your grid options.

```
<div data-ux-datagrid="data"
         data-grouped="'children'"
         data-addons="expandRows"
         data-options="{expandRows:[{template:'row', transition:false, swap:'expandedRow', state:'closed'}, {template:'expandedRow', transition: false, swap:'row', state:'opened', cls:'grid-row-open'}]}">
       <script type="template/html" template-item="row">
            <div class="row" data-ng-click="datagrid.expandRows.toggle($index)">
                <div class="col col1"><div></div></div>
                <div class="col col2"><div></div></div>
                <div class="col col3"><div></div></div>
                <div class="col col4"><div></div></div>
                <div class="col col5"><div></div></div>
            </div>
        </script>
       <script type="template/html" template-item="row">
            <div class="expandableRow-row" data-ng-click="datagrid.expandRows.toggle($index)">
                <div class="col col1"><div>Put Lots More Stuff in this template.</div></div>
                <div class="col col2"><div></div></div>
                <div class="col col3"><div></div></div>
                <div class="col col4"><div></div></div>
                <div class="col col5"><div></div></div>
            </div>
        </script>
    </div>
```

**Comment by bronzovik** [comment]
Hi Wes,
thank you for you reply. ```expandRows``` does not solve our problem. What we have is a grid started with all rows of the same height. One of the columns has arbitrary text in it. We need to implement 'expand all' functionality, when all rows expand to fit that text. So potentially they expand to different height. Having just one 'expanded row' template doesn't work, as internally the grid caches height on per template basis, not per row.
Thus, the crazy idea was to supply each row with its own template inheriting from basic one and just overriding the height. This is fine, but the grid does not do recalculations beyond active range. The problem we're trying to solve now is how to make it call ```calculateRowHeight()``` and update template height once a row scrolls into view.
Right now we have kinda working solution by having predefined 10 templates and assigning them based on content length approximations.

**Comment by wesjones** [comment]
Actually you can create an addon that will override the height value returned for each row. Then you can control the height of each row dynamically.

```
angular.module('ux').factory('overridesHeights', function () {
    return function (inst) {
        var $super = inst.getRowHeight;
        inst.getRowHeight = function (index) {
            var item = inst.getRowItem(index);// returns the data at that index.
            return item.myHeight || $super(index);
        };
    };
});
```

Please note that in doing this I highly recommend against using something like an element.offsetHeight because that is an expensive call to the browser element api. So if you do need to do this, make sure to cache it so you don't keep calling it.

You can use inst.getRowElm(index) to get the row element if you need it.

**Comment by bronzovik** [comment]
Hi Wes,

this won't work unfortunately :( getRowHeight() is only called from
calculateBottomOffset(). Regular row/chunks calculations are done from
updateTemplateHeights() which calls calculateRowHeight(el) for active
range and caches the result on per template basis.

**Comment by wesjones** [comment]
I think I finally see your problem.
I've got an experiment working that will allow dynamic row heights to work. However, it does come with a few gotchas that I'm trying to work out.
This will be a 1.4 release. I'll post back here when it is complete.

**Comment by wesjones** [comment]
1.4.1 just published.
[VaribleRowHeights](http://obogo.github.io/ux-angularjs-datagrid/#variableRowHeights)
Please try it out and let me know. Thanks.

**Comment by wesjones** [comment]
Did this work for you?

**Comment by bronzovik** [comment]
Hi Wes, it works somewhat. There are few glitches. The rendering is slower (which is expected) and there are overlapping rows sometimes. We are gonna stick to a predefined number of fixed height templates for now. Thanks a lot for working on this!

**Comment by wesjones** [comment]
Yes, I agree. The dynamic rows is really dynamic and caching values. So until those are calculate it doesn't know how large they can be which causes some overlapping. 
I think it will work for a lazy solution of dynamic rows and decent performance, however to get the best advantage would be to use the hard coded template values like you are using.

There is another way that you can use the same template. You can access scope().getGrid().templateModel.forceRowHeight(index, value); which was also newly added. You just want to set this after listening to the event of ux.datagrid.events.ON_BEFORE_RESET.

This may save you some work. It is similar to what you are doing, only instead of making a new template for each one, you just set the height for that row's index.
