### ISSUE TITLE
Use for grid of elements

### ISSUE THREAD

**Issue by robhicks** [obogo/ux-angularjs-datagrid#90]
Would ux-datagrid be suitable for a dynamic grid of fixed sized elements/cells, such as:
![batching](https://cloud.githubusercontent.com/assets/719152/13265029/1616ebf2-da2e-11e5-821a-d5c45d8dd423.png)
Each row gets filled based upon the width of browser. 

Currently, we are using vs-repeat. We calculate the size of rows before creating the grid and upon window resizing. Unfortunately, scrolling is jerky and element positioning in the grid can be problematical. 

We need to scale up to 5 ,000 cells. We're using angular 1.4. There are 9 bindings (4 are 2-way bindings) per cell.

If ux-datagrid would be suitable, can you make any recommendations about approach?

Thanks!

**Comment by wesjones** [comment]
Where you calculate the size of the rows before it is entered .... maybe.

The datagrid supports adding templates via js. http://obogo.github.io/ux-angularjs-datagrid/#templates

You could then dynamically create the templates with the number of elements inside of them and then add them to the grid rows. I would recommend it creates each one instead of having an ng-repeat in each row for performance.

Then the data that populates it would have to be in groups the size of the rows. So each row would just fill in from it's binds and it's indexed item's data for each box in a row.

**Comment by robhicks** [comment]
Thanks Wes. I'll give it a try.

**Comment by wesjones** [comment]
No problem. I would be interested to see how it goes.
