### ISSUE TITLE
windowScroll - scrollHistory is not restored

### ISSUE THREAD

**Issue by m4r71n** [obogo/ux-angularjs-datagrid#94]
I'm using the windowScroll and the scrollHistory addons. After destroying and rerender the grid (after a route change for instance) the scrollposition will not be restored.
I've created a demo [repo](https://github.com/m4r71n/ux-angularjs-datagrid_windowscroll-scrollhistory.git): `https://github.com/m4r71n/ux-angularjs-datagrid_windowscroll-scrollhistory.git`

**Comment by wesjones** [comment]
I really appreciate you providing the example. It was quite helpful.
The example was missing one crucial piece in order to make the scroll history work. The route of the browser mush change in order for history to be read and stored. 
Please note the changes I added with the document.location.hash in order to change the url so it matches and can store that value.

However, even with this there still was a bug, and that has been fixed in release 1.5.3 so it should work now as long as your address bar location.hash is changing.

```

        document.location.hash = '/on';
        angular
                .module("app", ['ng', 'ux'])
                .controller('controller', function ($scope) {
                    var i = 0;
                    var records = 100;

                    $scope.items = [];
                    while (i < records) {
                        $scope.items.push({id: i});
                        i += 1;
                    }

                    $scope.visible = true;
                    $scope.toggleVisibility = function () {
                        $scope.visible = !$scope.visible;
                        if ($scope.visible) {
                            document.location.hash = '/on';
                        } else {
                            document.location.hash = '/off';
                        }
                    }
                });

```

**Comment by m4r71n** [comment]
Thank you very much for your fast fix!
> The route of the browser mush change in order for history to be read and stored.

Are you really sure about this? I ask because with 07ee22ffccaa6f61774f4d6a38d99d4337a64b1f my demo even works without changing `document.location.hash`

**Comment by wesjones** [comment]
Yes, that is exactly what I mean. So you are saving them all on "" the empty string.
