### ISSUE TITLE
csp compatibility

### ISSUE THREAD

**Issue by m4r71n** [obogo/ux-angularjs-datagrid#98]
I'm trying to use a very strict set of content security policy rules including `style-src 'self'` which does not allow the use of `style`-attributes but modifing the style through the CSSOM is still allowed.
I've noticed that the html set via https://github.com/obogo/ux-angularjs-datagrid/blob/master/build/latest/angular-ux-datagrid.js#L3046 contains `style`-attributes.
Do you have any plans to make the datagrid compatible with `style-src 'self'`?

**Comment by wesjones** [comment]
It is an open source project. Feel free to commit a pull request with your changes.

**Comment by m4r71n** [comment]
Thanks. I'll try it.

**Comment by wesjones** [comment]
While the change looks easy enough. I'm not sure how this helps performance? We now have additional objects to evaluate during angular's digest cycle for these properties, rather than setting them directly on the element, which is what angular will be doing later is applying them directly to the style tag.

If what you are wanting to do is just escape some compiler that is looking for style= then that may be a better solution than this, because as I am looking at this with it now having to initialize another directive (per chunk) and also evaluate the object, create the object, etc. only to eventually set the style properties that we are already setting. I fail to see how this could do anything but hinder performance.

**Comment by m4r71n** [comment]
You're absolutely right. CSP compatibility will not improve the performance but [`ng-style`](https://github.com/angular/angular.js/blob/master/src/ng/directive/ngStyle.js) is using `css()` of `jqLite` which in turn is using [`element.style`](https://github.com/angular/angular.js/blob/master/src/jqLite.js#L634). 
With `style-src 'self'` set by the webserver the browser will not execute inline styles set via a `style`-attribute. For dynamic values you have to use `element.style`

I've updated the PR

**Comment by wesjones** [comment]
That is helpful, thank you. I now see why it wasn't working.

**Comment by m4r71n** [comment]
In the meantime I've realized that my PR #99 is not working as intended. 
First [`ngStyle`](https://docs.angularjs.org/api/ng/directive/ngStyle) needs an:
> Expression which evals to an object whose keys are CSS style names and values are corresponding values for those CSS keys.

Second the template for the chunks is not compiled with `$compile` so `ngStyle` has no effect. I believe the `style="height: ..."` I've seen in the rendered DOM came from [updateDomHeight](https://github.com/obogo/ux-angularjs-datagrid/blob/master/build/latest/angular-ux-datagrid.js#L3578).
I'm working on a solution and will send a PR.

**Comment by wesjones** [comment]
Because they don't run through the same life cycle as the rows. There would likely be a lot of changes to support this, and performance would reduce as a result. This also destroys the scope life cycle of the grid because now it will need to support parent scopes within the grid further reducing the performance. This would could make the grid too slow to be useful.
